on : [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: say hello
    steps:
    - name: hello world action step
      id: hello
      uses: Saad-Rahman-Warsi/my-javascript-actions@v1
      with:
        who-to-greet: 'Saad'
    - name: output
      run: echo "time was ${{steps.hello.outputs.time}}"   